#!/usr/bin/env bash
# func display information about subdomains
function dig_awk {
    pointer="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}')"
    record="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}')"
    printf "The subdomain %s is a %s record and points to %s\n" "$2" "$record" "$pointer"
    return 0
}

if [ $# -eq 2 ]
then
    dig_awk "$1" "$2"
else
    dig_awk "$1" "www"
    dig_awk "$1" "lb-01"
    dig_awk "$1" "web-01"
    dig_awk "$1" "web-02"
fi
exit 0
