#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
sudo service nginx restart
sudo bash -c 'echo "Holberton School" > /var/www/html/index.html'
str='rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
sudo sed -i "/# SSL configuration/$str/" /etc/nginx/sites-available/default
sudo service nginx restart
