#!/usr/bin/env bash
# install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
sudo service nginx restart
sudo bash -c 'echo "Holberton School" > /var/www/html/index.html'

# redirection
str='rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
sudo sed -i "/# SSL configuration/$str/" /etc/nginx/sites-available/default
sudo service nginx restart

#404
sudo bash -c "echo \"Ceci n'est pas une page\" > /usr/share/nginx/html/custom_404.html"
string="error_page 404 /custom_404.html;\
        location = /custom_404.html {\
                root /usr/share/nginx/html;\
                internal;\
        }"

#html header
string="add_header X-Served-By \$hostname;"
sudo sed -i "s/# listen 443 ssl default_server;/$string/" /etc/nginx/sites-available/default
sudo service nginx restart
