#!/usr/bin/env bash
# install and configure HAproxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

haprox_config="#--
#frontend http_front
bind *:80
stats uri /haproxy?stats
default_backend http_rear
#--
#backend http_rear
balance roundrobin
server 1652-web-01 34.75.248.37:80 check
server 1652-web-02 34.74.75.108:80 check"
sudo echo "$haprox_config" | tee -a /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | tee -a /etc/default/haproxy
sudo service haproxy restart
