#!/usr/bin/env bash
# debugging
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo sed -i 's/ ipv6only=on;/;/' /etc/nginx/sites-available/default
sudo service nginx restart
