#!/usr/bin/env bash
#  Script that displays numbers from 1 to 100 and does FIZZBUZZ

i="1"

while [ $i -le 100 ]
do
let fop=$i%3
let bop=$i%5
if [ "$fop" = "0" ] && [ "$bop" = "0" ]
then
	echo "FizzBuzz"
elif [ "$fop" = "0" ]
then
	echo "Fizz"
elif [ "$bop" = "0" ]
then
	echo "Buzz"
else
	echo "$i"
fi
let i+=1
done
