#!/usr/bin/env bash
path="/etc/passwd"
while field_sep=":" read -r a b c d e f g; do
	echo "The user $a is part of the $d gang, lives in $f and rides $g. $c's place is protected by the passcode $b, more info about the user here: $e"
done < $path
