#!/usr/bin/env bash
#  Script displays Holberton School 10 times but for 9th iteration, displays
#+ Holberton School and then hi on a newline

i="0"

while [ $i -lt 10 ]
do
if [ "$i" = "9" ]
then
	echo "Hi"
fi
echo "Holberton School"
i=$[$i+1]
done