#!/usr/bin/env bash
#  Script loops from 1-10 and displays bad luck on 4th iteration, good luck
#+ on 8th iteration, and Holberton School on all other iterations

i="0"

while [ $i -lt 10 ]
do
if [ "$i" = "3" ]
then
	echo "bad luck"
elif [ "$i" = "7" ]
then
	echo "good luck"
else
	echo "Holberton School"
fi
i=$i+1
done