#!/usr/bin/env bash
#  Script loops from 1-20 and displays "bad luck from China" on 4th iteration
#+ "bad luck from Japan" on 9th iteration and "bad luck from Italy" on 17th
#+ itertaion

i="1"

while [ $i -lt 21 ]
do
echo "$i"
case $i in
4)
	echo "bad luck from China"
	;;
9)
	echo "bad luck from Japan"
	;;
17)
	echo "bad luck from Italy"
	;;
esac
i=$[$i+1]
done