#!/usr/bin/env bash
# Script displays the time for 12 hours and 59 minutes

hour="0"

while [ $hour -lt 13 ]
do
	min="1"
	while [ $min -lt 60 ]
	do
		if [ "$min" = "1" ]
		then
			echo "Hour: $hour"
		fi
		echo "$min"
		let min+=1
	done
let hour+=1
done