#!/usr/bin/env bash
#  Script that displays the content of the current directory in list format
#+ where only the part of the name after the first dash is displayed

var= ls | cut -d '-' -f 2

for i in $var;
do
	echo "$i"
done