#!/usr/bin/env bash
# Script gives information about "holbertonschool" file

if [ -e "holbertonschool" ]
then
	echo "holbertonschool file exists"
	if [ -s "holbertonschool" ]
	then
		echo "holberton file is not empty"
	else
		echo "holberton file is empty"
	fi

	if [ -f "holbertonschool" ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holberton file does not exist"
fi